import { TechSkill } from '@/types';

export const techSkills: TechSkill[] = [
  {
    id: 'tech-python',
    title: 'Python',
    algorithmicLevel: 100,
    appliedLevel: 100,
    familiarityLevel: 90,
    mentorshipLevel: 100,
    years: 10,
    priority: 1,
    description: 'I love python and find myself using it everywhere even if a BASH script would suffice.',
    rgbad: 'rgba(105, 105, 255, 0.8)',
    rgbal: 'rgba(105, 105, 255, 0.8)',
  },
  {
    id: 'tech-ts',
    title: 'TypeScript',
    algorithmicLevel: 95,
    appliedLevel: 95,
    familiarityLevel: 95,
    mentorshipLevel: 100,
    years: 7,
    priority: 1,
    description: 'I enjoy TS more than JS',
    rgbad: 'rgba(55, 255, 10, 0.9)',
    rgbal: 'rgba(55, 255, 10, 0.9)',
  },
  {
    id: 'tech-js',
    title: 'JavaScript',
    algorithmicLevel: 95,
    appliedLevel: 90,
    familiarityLevel: 90,
    mentorshipLevel: 95,
    years: 10,
    priority: 1,
    description: 'simple/quick cannot do everything, but can do a lot',
    rgbad: 'rgba(150, 150, 150, 0.9)',
    rgbal: 'rgba(100, 100, 100, 0.8)',
  },
  {
    id: 'tech-cpp',
    title: 'C++',
    algorithmicLevel: 70,
    appliedLevel: 65,
    familiarityLevel: 65,
    mentorshipLevel: 70,
    years: 4.5,
    priority: 1,
    description: 'I like C++ more than C',
    rgbad: 'rgba(200, 160, 200, 1)',
    rgbal: 'rgba(165, 55, 165, 0.8)',
  },
  {
    id: 'tech-rust',
    title: 'Rust',
    algorithmicLevel: 40,
    appliedLevel: 30,
    familiarityLevel: 30,
    mentorshipLevel: 40,
    years: 2,
    priority: 1,
    description: 'I like Rust, but I don\'t use it much',
    rgbad: 'rgba(255, 255, 255, 0.8)',
    rgbal: 'rgba(55, 55, 55, 0.8)',
  },
  /* {
    id: 'tech-go',
    title: 'go',
    algorithmicLevel: 70,
    appliedLevel: 60,
    familiarityLevel: 60,
    mentorshipLevel: 40,
    years: 3,
    priority: 1,
    description: 'I like go, but I don\'t use it much',
    rgbad: 'rgba(5, 200, 5, 0.8)',
    rgbal: 'rgba(5, 155, 5, 0.8)',
  },
  {
    id: 'tech-haskell',
    title: 'Haskell',
    algorithmicLevel: 20,
    appliedLevel: 20,
    familiarityLevel: 10,
    mentorshipLevel: 10,
    years: 1.5,
    priority: 1,
    description: 'I was forced into using Haskell',
    rgbad: 'rgba(85, 85, 55, 1)',
    rgbal: 'rgba(85, 85, 55, 1)',
  }*/ {
    id: 'tech-react',
    title: 'React',
    algorithmicLevel: 80,
    appliedLevel: 90,
    familiarityLevel: 85,
    mentorshipLevel: 90,
    years: 5,
    priority: 3,
    description: 'I enjoy React more than Vue',
    rgbad: 'rgba(255, 155, 255, 0.8)',
    rgbal: 'rgba(55, 5, 55, 0.8)',
  },
  {
    id: 'tech-node',
    title: 'Node.js',
    algorithmicLevel: 80,
    appliedLevel: 80,
    familiarityLevel: 100,
    mentorshipLevel: 90,
    years: 7,
    priority: 3,
    description: 'An efficient server in node/express is like 40 times easier to set up than Django',
    rgbad: 'rgba(255, 255, 255, 0.8)',
    rgbal: 'rgba(55, 55, 55, 0.8)',
  },
  {
    id: 'tech-ml-tensorflow',
    title: 'TensorFlow',
    algorithmicLevel: 70,
    appliedLevel: 70,
    familiarityLevel: 70,
    mentorshipLevel: 80,
    years: 6,
    priority: 3,
    description: 'While TensorFlow is efficient, I am not a fan of using it.',
    rgbad: 'rgba(100, 100, 255, 0.9)',
    rgbal: 'rgba(0, 220, 170, 1)',
  },
  {
    id: 'tech-ml-pytorch',
    title: 'PyTorch',
    algorithmicLevel: 90,
    appliedLevel: 90,
    familiarityLevel: 90,
    mentorshipLevel: 100,
    years: 6,
    priority: 3,
    description: 'I enjoy pytorch more than tensorflow/keras. I like to use it for NLP',
    rgbad: 'rgba(200, 200, 255, 0.9)',
    rgbal: 'rgba(0, 120, 70, 1)',
  },
  {
    id: 'tech-k8',
    title: 'kubernetes',
    algorithmicLevel: 0,
    appliedLevel: 80,
    familiarityLevel: 80,
    mentorshipLevel: 80,
    years: 3,
    priority: 2,
    description: 'Kubernetes is the wild west still. I almost never understand CRDs',
    rgbad: 'rgba(255, 20, 20, 0.8)',
    rgbal: 'rgba(175, 20, 20, 0.95)',
  },
  {
    id: 'tech-docker',
    title: 'Docker',
    algorithmicLevel: 0,
    appliedLevel: 90,
    familiarityLevel: 100,
    mentorshipLevel: 100,
    years: 7,
    priority: 2,
    description: 'I love docker',
    rgbad: 'rgba(175, 175, 255, 0.4)',
    rgbal: 'rgba(5, 5, 55, 0.5)',
  },
  {
    id: 'tech-aws',
    title: 'AWS',
    algorithmicLevel: 0,
    appliedLevel: 80,
    familiarityLevel: 70,
    mentorshipLevel: 75,
    years: 7,
    priority: 2,
    description: 'AWS is so comprehensive. It constantly expands, like the universe.',
    rgbad: 'rgba(255, 255, 255, 0.8)',
    rgbal: 'rgba(55, 55, 55, 0.8)',
  },
  {
    id: 'tech-gcp',
    title: 'GCP',
    algorithmicLevel: 0,
    appliedLevel: 85,
    familiarityLevel: 90,
    mentorshipLevel: 90,
    years: 3,
    priority: 2,
    description: 'GCP is a lot easier to use than AWS and the abstractions make more sense',
    rgbad: 'rgba(5, 5, 255, 0.8)',
    rgbal: 'rgba(5, 5, 255, 0.8)',
  },
];
